### ISSUE TITLE
Can not close modal when ErrorBarier is displayed

### ISSUE THREAD

**Issue by crui3er** [Actual-Chat/actual-chat#1120]
![image](https://user-images.githubusercontent.com/20703715/229771780-353a5411-e547-4220-aaa6-5c89e1451893.png)

2023-04-04 14:56:28.858 +04:00 [ERR] Microsoft.AspNetCore.Components.Web.ErrorBoundary System.UnauthorizedAccessException: You can access only your own contacts.
   at Stl.Fusion.Client.RestEase.Internal.FusionHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.<SendAsync>g__Core|5_0(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at RestEase.Implementation.Requester.SendRequestAsync(IRequestInfo requestInfo, Boolean readBody)
   at RestEase.Implementation.Requester.RequestAsync[T](IRequestInfo requestInfo)
   at Stl.Fusion.Bridge.Interception.ReplicaMethodFunction`1.InvokeRemoteFunction(ComputeMethodInput input, CancellationToken cancellationToken)
   at Stl.Result`1.get_Value()
   at Stl.Fusion.FunctionBase`1.TryRecompute(ComputedInput input, IComputed usedBy, ComputeContext context, CancellationToken cancellationToken)
   at ActualChat.Contacts.ContactsExt.ListContacts(IContacts contacts, Session session, Func`2 filter, CancellationToken cancellationToken)
   at ActualChat.Chat.UI.Blazor.Components.NewChat.NewChatModal.OnInitializedAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
System.UnauthorizedAccessException: You can access only your own contacts.
   at Stl.Fusion.Client.RestEase.Internal.FusionHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.<SendAsync>g__Core|5_0(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at RestEase.Implementation.Requester.SendRequestAsync(IRequestInfo requestInfo, Boolean readBody)
   at RestEase.Implementation.Requester.RequestAsync[T](IRequestInfo requestInfo)
   at Stl.Fusion.Bridge.Interception.ReplicaMethodFunction`1.InvokeRemoteFunction(ComputeMethodInput input, CancellationToken cancellationToken)
   at Stl.Result`1.get_Value()
   at Stl.Fusion.FunctionBase`1.TryRecompute(ComputedInput input, IComputed usedBy, ComputeContext context, CancellationToken cancellationToken)
   at ActualChat.Contacts.ContactsExt.ListContacts(IContacts contacts, Session session, Func`2 filter, CancellationToken cancellationToken)
   at ActualChat.Chat.UI.Blazor.Components.NewChat.NewChatModal.OnInitializedAsync()
   at Microsoft.AspNetCore.Components.ComponentBase.RunInitAndSetParametersAsync()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)

**Comment by alexis-kochetov** [comment]
Closed as not planned during the September 2026 board cleanup: no activity for over a year. This is not a judgment on the idea. Reopen it if it is still relevant, and add it to a current release milestone.
