### ISSUE TITLE
Failed to process mention during executing 'copy chat' operation. Id duplication.

### ISSUE THREAD

**Issue by crui3er** [Actual-Chat/actual-chat#1990]
OnCopyChat(f3a4eb45-7976-47b0-babe-5369125dd8d3) failed to proceed chat entries insertion for range [6501, 24174)
```
System.InvalidOperationException: The instance of entity type 'DbMention' cannot be tracked because another instance with the same key value for {'Id'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.
at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.ThrowIdentityConflict(InternalEntityEntry entry)   
at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry, Boolean updateDuplicate)
at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry)  
at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NullableKeyIdentityMap`1.Add(InternalEntityEntry entry)  
at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking(InternalEntityEntry entry) 
at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges, Boolean modifyProperties)   
at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode`1 node)   
at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)   
at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.AttachGraph(InternalEntityEntry rootEntry, EntityState targetState, EntityState storeGeneratedWithKeySetTargetState, Boolean forceStateWhenUnknownKey)   
at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.SetEntityState(InternalEntityEntry entry, EntityState entityState)   
at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.Add(TEntity entity)   
at ActualChat.Chat.ChatsBackend.InsertMentions(ChatDbContext dbContext, String chatSid, ChatId newChatId, String correlationId, Range`1 range, MigratedAuthors migratedAuthors, ICollection`1 entryIdsCollector, CancellationToken cancellationToken)
	in /_/src/dotnet/Chat.Service/ChatsBackend.CopyChat.cs:line 755
at ActualChat.Chat.ChatsBackend.CopyChatEntries(ChatDbContext dbContext, CopyChatEntriesContext context, ChatEntryKind entryKind, Range`1 entryIdRange, Int32 batchLimit, CancellationToken cancellationToken)
	in /_/src/dotnet/Chat.Service/ChatsBackend.CopyChat.cs:line 387   
at ActualChat.Chat.ChatsBackend.CopyChatEntries(CopyChatEntriesContext context, Range`1 entryIdRange, Int32 batchLimit, CancellationToken cancellationToken) 
	in /_/src/dotnet/Chat.Service/ChatsBackend.CopyChat.cs:line 318   
at ActualChat.Chat.ChatsBackend.CopyChatEntries(CopyChatEntriesContext context, Range`1 entryIdRange, Int32 batchLimit, CancellationToken cancellationToken) 
	in /_/src/dotnet/Chat.Service/ChatsBackend.CopyChat.cs:line 340   
at ActualChat.Chat.ChatsBackend.OnCopyChat(ChatBackend_CopyChat command, CancellationToken cancellationToken) 
	in /_/src/dotnet/Chat.Service/ChatsBackend.CopyChat.cs:line 119
```

**Comment by crui3er** [comment]
At some point DbMention.AuthorId field (later renamed to MentionId) mistakenly hold value of author of text entry instead of mentioned author. Fixed in https://github.com/Actual-Chat/actual-chat/commit/de35ccfe1f756546bdb68c7ada016791773637a1
