### ISSUE TITLE
Some link previews are not generated

### ISSUE THREAD

**Issue by frolyo** [Actual-Chat/actual-chat#2019]

**Comment by crui3er** [comment]
OpenGraphParser can not handle multiple 'og:video:tag' properties which quite common.
E.g. see https://console.cloud.google.com/logs/query;cursorTimestamp=2024-05-02T11:27:04.685107814Z;duration=PT15M;query=resource.labels.container_name%3D%22actual-chat-app%22%0Aseverity%3E%3DNOTICE%0Atimestamp%3D%222024-05-02T11:27:04.685107814Z%22%0AinsertId%3D%22b7oyp6lmmckeedn1%22?project=actual-chat-app-prod

**Comment by crui3er** [comment]
OpenGraphParser can not handle multiple 'og:description' properties.

Failed link: https://www.marktechpost.com/2023/12/27/myshell-open-sources-openvoice-an-instant-voice-cloning-ai-library-that-takes-a-short-audio-clip-from-the-reference-speaker-and-generate-speech-in-multiple-language/

https://console.cloud.google.com/logs/query;cursorTimestamp=2024-05-06T13:32:52.733890265Z;duration=PT5M;query=resource.labels.container_name%3D%22actual-chat-app%22%0Aseverity%3E%3DDEBUG%0Atimestamp%3D%222024-05-06T13:32:52.732518945Z%22%0AinsertId%3D%22o981aod8jravxlg1%22?project=actual-chat-app-prod

**Comment by crui3er** [comment]
insertId: "up1u6j9j2dzpudii"

Failed link: https://arxiv.org/abs/2403.14403

```
System.NotSupportedException: The 'file' scheme is not supported.
   at Microsoft.Extensions.Http.Logging.LoggingHttpMessageHandler.<SendCoreAsync>g__Core|5_0(HttpRequestMessage request, Boolean useAsync, CancellationToken cancellationToken)
   at Microsoft.Extensions.Http.Logging.LoggingScopeHttpMessageHandler.<SendCoreAsync>g__Core|5_0(HttpRequestMessage request, Boolean useAsync, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at ActualChat.Media.ImageGrabber.<>c__DisplayClass14_0.<<DownloadImageToFile>g__Download|0>d.MoveNext() in /_/src/dotnet/Media.Service/ImageGrabber.cs:line 87
--- End of stack trace from previous location ---
   at ActualChat.Media.ImageGrabber.DownloadImageToFile(String imageUrl, CancellationToken cancellationToken) in /_/src/dotnet/Media.Service/ImageGrabber.cs:line 83
   at ActualChat.Media.ImageGrabber.GrabImage(String imageUri, CancellationToken cancellationToken) in /_/src/dotnet/Media.Service/ImageGrabber.cs:line 26
   at ActualChat.Media.WebSiteHandler.Handle(HttpResponseMessage response, CancellationToken cancellationToken) in /_/src/dotnet/Media.Service/WebSiteHandler.cs:line 19
   at ActualChat.Media.Crawler.Crawl(String url, CancellationToken cancellationToken) in /_/src/dotnet/Media.Service/Crawler.cs:line 37
   at ActualChat.Media.LinkPreviewsBackend.RefreshUnsafe(Symbol id, String url, CancellationToken cancellationToken) in /_/src/dotnet/Media.Service/LinkPreviewsBackend.cs:line 84
   at ActualChat.Media.LinkPreviewsBackend.<>c__DisplayClass13_0.<<OnRefresh>g__RefreshTaskFactory|0>d.MoveNext() in /_/src/dotnet/Media.Service/LinkPreviewsBackend.cs:line 64
--- End of stack trace from previous location ---
   at ActualChat.Mesh.MeshLocksExt.TryRunLocked[T](IMeshLocks meshLocks, String key, RunLockedOptions options, Boolean exitIfLocked, Func`2 taskFactory, CancellationToken cancellationToken) in /_/src/dotnet/Core.Server/Mesh/Locking/MeshLocksExt.RunLocked.cs:line 78
   at ActualChat.Mesh.MeshLocksExt.TryRunLocked[T](IMeshLocks meshLocks, String key, RunLockedOptions options, Boolean exitIfLocked, Func`2 taskFactory, CancellationToken cancellationToken) in /_/src/dotnet/Core.Server/Mesh/Locking/MeshLocksExt.RunLocked.cs:line 100
   at ActualChat.Media.LinkPreviewsBackend.OnRefresh(LinkPreviewsBackend_Refresh command, CancellationToken cancellationToken) in /_/src/dotnet/Media.Service/LinkPreviewsBackend.cs:line 56
   at ActualLab.CommandR.CommandContext`1.InvokeRemainingHandlers(CancellationToken cancellationToken)
   at ActualLab.Fusion.EntityFramework.Operations.DbOperationScopeProvider.OnCommand(ICommand command, CommandContext context, CancellationToken cancellationToken) in /_/src/ActualLab.Fusion.EntityFramework/Operations/DbOperationScopeProvider.cs:line 28
   at ActualLab.Fusion.EntityFramework.Operations.DbOperationScopeProvider.OnCommand(ICommand command, CommandContext context, CancellationToken cancellationToken) in /_/src/ActualLab.Fusion.EntityFramework/Operations/DbOperationScopeProvider.cs:line 60
   at ActualLab.CommandR.CommandContext`1.InvokeRemainingHandlers(CancellationToken cancellationToken) in /_/src/ActualLab.CommandR/CommandContext.cs:line 188
   at ActualLab.Fusion.Operations.Internal.TransientOperationScopeProvider.OnCommand(ICommand command, CommandContext context, CancellationToken cancellationToken) in /_/src/ActualLab.Fusion/Operations/Internal/TransientOperationScopeProvider.cs:line 36
```

https://console.cloud.google.com/logs/query;cursorTimestamp=2024-05-06T13:57:06.004805102Z;duration=PT30M;query=resource.labels.container_name%3D%22actual-chat-app%22%0Aseverity%3E%3DWARNING%0Atimestamp%3D%222024-05-06T13:57:05.305329736Z%22%0AinsertId%3D%22up1u6j9j2dzpudii%22?project=actual-chat-app-prod
