### ISSUE TITLE
Failed to update external contact

### ISSUE THREAD

**Issue by crui3er** [Actual-Chat/actual-chat#2041]
Found a series of errors in the log with message like "Failed to update external contact"

insertId: "u7zvwnq0vrfg1zhe",

```
ActualLab.Versioning.VersionMismatchException: Version mismatch.
at ActualLab.Versioning.VersionChecker.RequireExpected[TVersion](TVersion version, TVersion expectedVersion)
   in /_/src/ActualLab.Core/Versioning/VersionChecker.cs:line 10
at ActualChat.HasVersionExt.RequireVersion[TEntity](TEntity entity, Nullable`1 expectedVersion)
   in /_/src/dotnet/Core/HasVersionExt.cs:line 29
at ActualChat.Contacts.ExternalContactsBackend.ChangeItem(ExternalContactChange itemChange, CancellationToken cancellationToken)
   in /_/src/dotnet/Contacts.Service/ExternalContactsBackend.cs:line 162
at ActualChat.Contacts.ExternalContactsBackend.ChangeItem(ExternalContactChange itemChange, CancellationToken cancellationToken)
   in /_/src/dotnet/Contacts.Service/ExternalContactsBackend.cs:line 179
at ActualChat.Contacts.ExternalContactsBackend.OnBulkChange(ExternalContactsBackend_BulkChange command, CancellationToken cancellationToken)
   in /_/src/dotnet/Contacts.Service/ExternalContactsBackend.cs:line 116
```

https://console.cloud.google.com/logs/query;query=resource.labels.container_name%3D%22actual-chat-app%22%0Aseverity%3E%3DWARNING;cursorTimestamp=2024-05-06T13:38:42.100501135Z;aroundTime=2024-05-06T13:39:00.000Z;duration=PT1M?project=actual-chat-app-prod

**Comment by alexis-kochetov** [comment]
Closed as not planned during the September 2026 board cleanup: no activity for over a year. This is not a judgment on the idea. Reopen it if it is still relevant, and add it to a current release milestone.
